In [10]:
from keras.models import Sequential , Model
from keras.layers import Dense , Flatten
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold,cross_val_score,StratifiedKFold
# from keras.wrappers.scikit_learn import KerasClassifier


In [11]:
model=Sequential()
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [12]:
data=pd.read_csv("creditcard.csv")
data.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [13]:
data.tail(5)

Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[5 rows x 31 columns]

In [14]:
x=data
y=data['Class']

In [15]:
data.nunique()

Time      124592
V1        275663
V2        275663
V3        275663
V4        275663
V5        275663
V6        275663
V7        275663
V8        275663
V9        275663
V10       275663
V11       275663
V12       275663
V13       275663
V14       275663
V15       275663
V16       275663
V17       275663
V18       275663
V19       275663
V20       275663
V21       275663
V22       275663
V23       275663
V24       275663
V25       275663
V26       275663
V27       275663
V28       275663
Amount     32767
Class          2
dtype: int64

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
x_train

array([[ 0.75665415,  1.04272047,  0.06657394, ..., -0.2607924 ,
        -0.35356699, -0.04176806],
       [-0.2834455 ,  0.65277143,  0.27902921, ..., -0.01672827,
        -0.34945825, -0.04176806],
       [ 1.35155922, -0.21266203,  0.00863513, ...,  0.631378  ,
        -0.33270102, -0.04176806],
       ...,
       [-0.38298583,  0.77014889, -0.57187168, ...,  0.01108282,
        -0.21608519, -0.04176806],
       [ 0.05149257,  0.91611288, -1.02491801, ..., -0.100612  ,
         0.33339889, -0.04176806],
       [-0.41938711, -0.30165824,  0.45289483, ...,  0.36475181,
        -0.29225808, -0.04176806]])

In [17]:
# Split the data into features (X) and target (y) for both Class 1 and Class 0

# For Class 1 (fraudulent transactions)
class_1_data = data[data['Class'] == 1]
x_test = class_1_data.drop('Class', axis=1)  # Features for Class 1
y_test = class_1_data['Class']  # Target for Class 1

# For Class 0 (non-fraudulent transactions)
class_0_data = data[data['Class'] == 0]
x_train = class_0_data.drop('Class', axis=1)   # Features for Class 0
y_train = class_0_data['Class']  # Target for Class 0


In [18]:
print(x_train[0:5])

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24  \
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27 

In [19]:
print(y_train[0:5])

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64


In [20]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
8885/8885 ━━━━━━━━━━━━━━━━━━━━ 28s 3ms/step - accuracy: 1.0000 - loss: 1.7540e-07
Epoch 2/20
8885/8885 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 1.0000 - loss: 0.0000e+00
Epoch 3/20
5263/8885 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 1.0000 - loss: 0.0000e+00

KeyboardInterrupt: 

In [28]:
prediction=model.predict(x_test)

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step


In [29]:
print(np.argmax(prediction[0]))

0


In [30]:
print(y_test[0:5])

541     1
623     1
4920    1
6108    1
6329    1
Name: Class, dtype: int64


In [35]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(prediction, np.zeros(y_test.shape))
print(f"Accuracy on test set: {accuracy}")

Accuracy on test set: 1.0


In [45]:
kfold=KFold(n_splits=3,shuffle=True,random_state=42)


In [46]:
for train_index,test_index in kfold.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index,test_index)

[2 3 4 6 7 9] [0 1 5 8]
[0 1 3 4 5 6 8] [2 7 9]
[0 1 2 5 7 8 9] [3 4 6]


In [58]:
def create_baseline():
  model=Sequential()
  model.add(Dense(128,activation='relu'))
  model.add(Dense(128,activation='relu'))
  model.add(Dense(128,activation='relu'))
  model.add(Dense(128,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model
estimator=KerasClassifier(build_fn=create_baseline,epochs=10,batch_size=5)
kfold=KFold(n_splits=2,shuffle=True)
results=cross_val_score(estimator,x,y,cv=kfold)
print(results.mean()*100)

C:\Users\h8551\AppData\Local\Temp\ipykernel_28596\596326256.py:10: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  estimator=KerasClassifier(build_fn=create_baseline,epochs=10,batch_size=5)


ValueError: epochs is not a legal parameter